---
- id: go-format
  name: go format
  description: Runs `gofumpt` and asserts no changes are needed.
  entry: hooks/go-format.sh
  language: script
  files: \.go$

- id: go-deadcode
  name: go-deadcode
  description: Runs `deadcode` and asserts no changes are needed.
  entry: hooks/go-deadcode.sh
  language: script
  types: [go]
  require_serial: true
  pass_filenames: false

- id: forbid-binary
  name: Forbid binaries
  description: Forbid binary files from being committed
  entry: hooks/forbid-binary.sh
  language: script
  types: ["binary"]

- id: shellcheck
  name: Test shell scripts with shellcheck
  description: Shell scripts conform to shellcheck
  entry: hooks/shellcheck.sh
  language: script
  types: [shell]
  exclude_types: [csh, perl, python, ruby, tcsh, zsh]
  args: [-e, SC1091]

- id: shfmt
  name: Check shell style with shfmt
  language: script
  entry: hooks/shfmt.sh
  types: [shell]
  exclude_types: [csh, perl, python, ruby, tcsh, zsh]
  args: ["-l", "-i", "2", "-ci"]

- id: docker-compose-check
  name: Validate docker-compose files
  description: Checks that docker-compose files are valid
  language: script
  entry: hooks/compose-check.sh
  files: docker-compose.y[a]{0,1}ml$

- id: snake-case-filenames
  name: Filenames must be in snake case
  entry: filenames must be snake_case
  language: fail
  files: '[a-z0-9_/]*[^a-z0-9_/]+[a-z0-9_]*\.(go|py|lua|sh)$'
